on:
  push:
    branches: [main,'release/**']
  pull_request:
    branches: [main,'release/**']

name: Ethereum Tests

jobs:
  tests-stable:
    name: Ethereum Tests (Stable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Checkout ethereum/tests
        uses: actions/checkout@v2
        with:
          repository: ethereum/tests
          path: ethtests
          submodules: recursive,

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Run Ethereum tests
        run: cargo run --profile ethtests -p revme -- statetest ethtests/GeneralStateTests ethtests/LegacyTests/Constantinople/GeneralStateTests/
