apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: tony-lend
  annotations:
    type: PWN
    name: Tony Lend
    description: ""
    author: ""
    tags: "pwn"
    flag: "blaz{T0ny_l3nds_but_nev3r_r3c3ives}"

spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  podTemplate:
    template:
      spec:
        serviceAccountName: default
        automountServiceAccountToken: true
        containers:
          - name: challenge
            resources:
              limits:
                memory: 4G
                cpu: "1"