flag: DH{flag}SAMPLEFLAG
L2_TOKEN: "0x5a8a905508532d4C98D1f8318233A96FeFb4cEbc"
BRIDGE: "0x15c4cA379fce93A279ac49222116A443B972C777"
# YOU MUST NOT CHANGE THE RELAYER KEY
# GENESIS STATES ARE BASED ON THIS KEY (BRIDGE / TOKEN ADDRESS ...)
RELAYER_PVKEY: "<CONFIDENTIAL>"
