---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-blockchain
  template:
    metadata:
      labels:
        app: enterprise-blockchain
    spec:
      containers:
      - name: enterprise-blockchain
        image: us.gcr.io/blaz-ctf-435008/enterprise-blockchain:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8848
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: enterprise-blockchain-service
spec:
  type: LoadBalancer
  ports:
  - port: 8848
    targetPort: 8848
  selector:
    app: enterprise-blockchain